[package]
name = "sanchir-rust"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web="4.10.2"
tokio = { version = "1.44.0", features = ["full"] }
serde ={version = "1.0.219",features = ["derive"]}
dotenvy = "0.15.7"
diesel = { version = "2.2.8", features = ["postgres","uuid","chrono","r2d2"] }
serde_json = "1.0.140"

