[package]
name = "rust-actix"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web="4.10.2"
tokio = { version = "1.44.0", features = ["full"] }
serde ={version = "1.0.219",features = ["derive"]}
sqlx ={version="0.8.3", features=["postgres","runtime-tokio-rustls", "derive"]}
dotenvy = "0.15.7"
serde_json = "1.0.140"
config = "0.15.9"

