version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["make", "run-prod"]
    restart: always
    image: rust-axum
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=rust-axum
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_HOST='0.0.0.0'
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  db:
  redis:
