version: "3.8"

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=rust-actixt
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  db:
  redis:
