[database]
username = "postgres"
password = "postgres"
host = "localhost"
port = 5433
database = "rust-axum"
retry = 3

[logger]
level = "debug"
pretty = true
file_path = ""

[redis]


[http_server]
port = 5000
host = "0.0.0.0"
