// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CandlesStruct = {
  id: string;
  title: string;
  slug: string;
  version: bigint;
  price: bigint;
  color_id: string;
};
