// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorsStruct = {
  id: string;
  name: string;
  slug: string;
  version: bigint;
};
