// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCandleRequest = {
  color_id: string;
  title: string;
  version: bigint;
  price: bigint;
};
